import type { SettingsSection } from "renderer/stores/settings-state";
import { SUPPORTS_AGENT_SLEEP_PREVENTION } from "shared/constants";

export const SETTING_ITEM_ID = {
	ACCOUNT_PROFILE: "account-profile",
	ACCOUNT_SIGNOUT: "account-signout",

	ORGANIZATION_LOGO: "organization-logo",
	ORGANIZATION_NAME: "organization-name",
	ORGANIZATION_SLUG: "organization-slug",
	ORGANIZATION_MEMBERS_LIST: "organization-members-list",
	ORGANIZATION_MEMBERS_INVITE: "organization-members-invite",
	ORGANIZATION_MEMBERS_PENDING_INVITATIONS:
		"organization-members-pending-invitations",

	APPEARANCE_THEME: "appearance-theme",
	APPEARANCE_MARKDOWN: "appearance-markdown",
	APPEARANCE_CUSTOM_THEMES: "appearance-custom-themes",
	APPEARANCE_EDITOR_FONT: "appearance-editor-font",
	APPEARANCE_TERMINAL_FONT: "appearance-terminal-font",
	APPEARANCE_VIBRANCY: "appearance-vibrancy",

	RINGTONES_NOTIFICATION: "ringtones-notification",
	RINGTONES_AIVIS: "ringtones-aivis",
	RINGTONES_AIVIS_DICTIONARY: "ringtones-aivis-dictionary",
	RINGTONES_AIVIS_USAGE: "ringtones-aivis-usage",

	KEYBOARD_SHORTCUTS: "keyboard-shortcuts",
	BEHAVIOR_CONFIRM_QUIT: "behavior-confirm-quit",
	BEHAVIOR_TELEMETRY: "behavior-telemetry",
	BEHAVIOR_PREVENT_AGENT_SLEEP: "behavior-prevent-agent-sleep",
	BEHAVIOR_FILE_OPEN_MODE: "behavior-file-open-mode",
	BEHAVIOR_FILE_DRAG_BEHAVIOR: "behavior-file-drag-behavior",
	BEHAVIOR_RIGHT_SIDEBAR_OPEN_VIEW_WIDTH:
		"behavior-right-sidebar-open-view-width",
	BEHAVIOR_RESOURCE_MONITOR: "behavior-resource-monitor",
	BEHAVIOR_OPEN_LINKS_IN_APP: "behavior-open-links-in-app",
	BEHAVIOR_LANGUAGE_DIAGNOSTICS: "behavior-language-diagnostics",

	GIT_BRANCH_PREFIX: "git-branch-prefix",
	GIT_DELETE_LOCAL_BRANCH: "git-delete-local-branch",
	GIT_WORKTREE_LOCATION: "git-worktree-location",
	GIT_SMART_COMMIT: "git-smart-commit",
	GIT_AUTO_STASH: "git-auto-stash",
	GIT_BRANCH_SORT_ORDER: "git-branch-sort-order",
	GIT_POST_COMMIT_COMMAND: "git-post-commit-command",

	AGENTS_ENABLED: "agents-enabled",
	AGENTS_COMMANDS: "agents-commands",
	AGENTS_TASK_PROMPTS: "agents-task-prompts",

	TERMINAL_PRESETS: "terminal-presets",
	TERMINAL_QUICK_ADD: "terminal-quick-add",
	TERMINAL_SESSIONS: "terminal-sessions",
	TERMINAL_SUGGESTIONS: "terminal-suggestions",
	TERMINAL_LINK_BEHAVIOR: "terminal-link-behavior",

	LINKS_FILE: "links-file",
	LINKS_URL: "links-url",

	MODELS_ANTHROPIC: "models-anthropic",
	MODELS_OPENAI: "models-openai",
	MODELS_NEXT_EDIT: "models-next-edit",

	EXPERIMENTAL_SUPERSET_V2: "experimental-superset-v2",
	EXPERIMENTAL_V1_MIGRATION: "experimental-v1-migration",

	INTEGRATIONS_LINEAR: "integrations-linear",
	INTEGRATIONS_GITHUB: "integrations-github",
	INTEGRATIONS_SLACK: "integrations-slack",

	BILLING_OVERVIEW: "billing-overview",
	BILLING_PLANS: "billing-plans",
	BILLING_USAGE: "billing-usage",

	PROJECT_NAME: "project-name",
	PROJECT_PATH: "project-path",
	PROJECT_SCRIPTS: "project-scripts",
	PROJECT_BRANCH_PREFIX: "project-branch-prefix",
	PROJECT_WORKTREE_LOCATION: "project-worktree-location",
	PROJECT_IMPORT_WORKTREES: "project-import-worktrees",
	PROJECT_AUTO_IMPORT_WORKTREES: "project-auto-import-worktrees",
	PROJECT_AUTO_REMOVE_WORKTREES: "project-auto-remove-worktrees",
	PROJECT_ENV_VARS: "project-env-vars",

	API_KEYS_LIST: "api-keys-list",
	API_KEYS_GENERATE: "api-keys-generate",

	EXTENSIONS_BROWSER: "extensions-browser",

	VSCODE_EXTENSIONS_MANAGE: "vscode-extensions-manage",
	VSCODE_EXTENSIONS_INDENT_RAINBOW: "vscode-extensions-indent-rainbow",
	VSCODE_EXTENSIONS_TRAILING_SPACES: "vscode-extensions-trailing-spaces",
	VSCODE_EXTENSIONS_REFERENCE_GRAPH: "vscode-extensions-reference-graph",

	METRICS_GITHUB_OVERVIEW: "metrics-github-overview",
	METRICS_GITHUB_TRAFFIC: "metrics-github-traffic",
	METRICS_GITHUB_COPY: "metrics-github-copy",

	SERVICE_STATUS_PROVIDERS: "service-status-providers",
	SERVICE_STATUS_ADD: "service-status-add",

	PERMISSIONS_FULL_DISK_ACCESS: "permissions-full-disk-access",
	PERMISSIONS_ACCESSIBILITY: "permissions-accessibility",
	PERMISSIONS_MICROPHONE: "permissions-microphone",
	PERMISSIONS_CAMERA: "permissions-camera",
	PERMISSIONS_APPLE_EVENTS: "permissions-apple-events",
	PERMISSIONS_LOCAL_NETWORK: "permissions-local-network",

	SECURITY_EXPOSE_HOST_SERVICE_VIA_RELAY:
		"security-expose-host-service-via-relay",

	HOST_MEMBERS: "host-members",
	HOST_INVITE_MEMBER: "host-invite-member",
	HOST_MEMBER_ROLE: "host-member-role",
} as const;

export type SettingItemId =
	(typeof SETTING_ITEM_ID)[keyof typeof SETTING_ITEM_ID];

export interface SettingsItem {
	id: SettingItemId;
	section: SettingsSection;
	title: string;
	description: string;
	keywords: string[];
}

export const SETTINGS_ITEMS: SettingsItem[] = [
	{
		id: SETTING_ITEM_ID.ACCOUNT_PROFILE,
		section: "account",
		title: "Profile",
		description: "Your profile information",
		keywords: [
			"account",
			"name",
			"email",
			"avatar",
			"user",
			"profile",
			"picture",
			"photo",
			"me",
		],
	},
	{
		id: SETTING_ITEM_ID.ACCOUNT_SIGNOUT,
		section: "account",
		title: "Sign Out",
		description: "Sign out of your account",
		keywords: [
			"account",
			"sign out",
			"logout",
			"log out",
			"disconnect",
			"leave",
		],
	},
	{
		id: SETTING_ITEM_ID.ORGANIZATION_LOGO,
		section: "organization",
		title: "Organization Logo",
		description: "Upload and manage your organization's logo",
		keywords: [
			"organization",
			"logo",
			"image",
			"branding",
			"upload",
			"icon",
			"picture",
			"avatar",
		],
	},
	{
		id: SETTING_ITEM_ID.ORGANIZATION_NAME,
		section: "organization",
		title: "Organization Name",
		description: "Change your organization's display name",
		keywords: [
			"organization",
			"name",
			"rename",
			"title",
			"company",
			"team name",
		],
	},
	{
		id: SETTING_ITEM_ID.ORGANIZATION_SLUG,
		section: "organization",
		title: "Organization Slug",
		description: "Your organization's unique identifier",
		keywords: [
			"organization",
			"slug",
			"url",
			"identifier",
			"subdomain",
			"link",
			"unique",
		],
	},
	{
		id: SETTING_ITEM_ID.ORGANIZATION_MEMBERS_LIST,
		section: "organization",
		title: "Team Members",
		description: "View and manage team members and their roles",
		keywords: [
			"organization",
			"members",
			"team",
			"users",
			"roles",
			"people",
			"collaborators",
			"permissions",
			"access",
			"admin",
			"owner",
		],
	},
	{
		id: SETTING_ITEM_ID.ORGANIZATION_MEMBERS_INVITE,
		section: "organization",
		title: "Invite Members",
		description: "Invite new members to your organization",
		keywords: [
			"organization",
			"members",
			"invite",
			"add",
			"new member",
			"team",
			"share",
			"collaborate",
			"email",
			"send invite",
		],
	},
	{
		id: SETTING_ITEM_ID.ORGANIZATION_MEMBERS_PENDING_INVITATIONS,
		section: "organization",
		title: "Pending Invitations",
		description: "View and manage pending organization invitations",
		keywords: [
			"organization",
			"members",
			"invite",
			"invitation",
			"pending",
			"team",
			"waiting",
			"sent",
			"cancel",
			"resend",
			"email",
		],
	},
	{
		id: SETTING_ITEM_ID.APPEARANCE_THEME,
		section: "appearance",
		title: "Theme",
		description: "Choose your theme",
		keywords: [
			"appearance",
			"theme",
			"dark",
			"light",
			"dark mode",
			"light mode",
			"colors",
			"night",
			"system",
			"visual",
		],
	},
	{
		id: SETTING_ITEM_ID.APPEARANCE_MARKDOWN,
		section: "appearance",
		title: "Markdown Style",
		description: "Rendering style for markdown files",
		keywords: [
			"appearance",
			"markdown",
			"style",
			"tufte",
			"rendering",
			"preview",
			"format",
			"display",
			"md",
			"readme",
		],
	},
	{
		id: SETTING_ITEM_ID.APPEARANCE_CUSTOM_THEMES,
		section: "appearance",
		title: "Custom Themes",
		description: "Import custom theme files",
		keywords: [
			"appearance",
			"custom",
			"themes",
			"import",
			"json",
			"color scheme",
			"upload",
			"personalize",
			"customize",
		],
	},
	{
		id: SETTING_ITEM_ID.APPEARANCE_EDITOR_FONT,
		section: "appearance",
		title: "Editor Font",
		description: "Font used in diff views and file editors",
		keywords: [
			"appearance",
			"font",
			"family",
			"size",
			"editor",
			"diff",
			"mono",
			"monospace",
			"typography",
			"custom",
		],
	},
	{
		id: SETTING_ITEM_ID.APPEARANCE_TERMINAL_FONT,
		section: "appearance",
		title: "Terminal Font",
		description: "Font used in terminal panels",
		keywords: [
			"appearance",
			"font",
			"family",
			"size",
			"terminal",
			"mono",
			"monospace",
			"typography",
			"custom",
			"nerd",
		],
	},
	{
		id: SETTING_ITEM_ID.APPEARANCE_VIBRANCY,
		section: "appearance",
		title: "Window Vibrancy",
		description: "Make the window semi-transparent with a macOS vibrancy blur",
		keywords: [
			"appearance",
			"vibrancy",
			"transparent",
			"transparency",
			"blur",
			"opacity",
			"glass",
			"warp",
			"macos",
			"ウィンドウ透過",
			"不透明度",
			"ブラー",
		],
	},
	{
		id: SETTING_ITEM_ID.RINGTONES_NOTIFICATION,
		section: "ringtones",
		title: "Notification Sound",
		description: "Choose the notification sound for completed tasks",
		keywords: [
			"notifications",
			"notification",
			"sound",
			"ringtone",
			"audio",
			"alert",
			"bell",
			"tone",
			"complete",
			"done",
			"finished",
			"chime",
			"mute",
			"volume",
		],
	},
	{
		id: SETTING_ITEM_ID.RINGTONES_AIVIS,
		section: "ringtones",
		title: "Aivis Voice Announcement",
		description:
			"Speak the workspace/branch via Aivis API after the notification sound",
		keywords: [
			"aivis",
			"tts",
			"voice",
			"speech",
			"announce",
			"読み上げ",
			"音声合成",
			"アイビス",
		],
	},
	{
		id: SETTING_ITEM_ID.RINGTONES_AIVIS_DICTIONARY,
		section: "ringtones",
		title: "Aivis User Dictionary",
		description:
			"Register custom pronunciations for branch names, acronyms, and proper nouns",
		keywords: [
			"aivis",
			"dictionary",
			"pronunciation",
			"辞書",
			"読み方",
			"カスタム読み",
			"固有名詞",
		],
	},
	{
		id: SETTING_ITEM_ID.RINGTONES_AIVIS_USAGE,
		section: "ringtones",
		title: "Aivis Usage",
		description: "Daily Aivis API request count, characters and credits",
		keywords: [
			"aivis",
			"usage",
			"credits",
			"使用量",
			"クレジット",
			"リクエスト",
		],
	},
	{
		id: SETTING_ITEM_ID.KEYBOARD_SHORTCUTS,
		section: "keyboard",
		title: "Keyboard Shortcuts",
		description: "View and customize keyboard shortcuts",
		keywords: [
			"keyboard",
			"shortcuts",
			"hotkeys",
			"keys",
			"bindings",
			"keybindings",
			"commands",
			"ctrl",
			"cmd",
			"alt",
			"customize",
		],
	},
	{
		id: SETTING_ITEM_ID.BEHAVIOR_CONFIRM_QUIT,
		section: "behavior",
		title: "Confirm before quitting",
		description: "Show a confirmation dialog when quitting the app",
		keywords: [
			"features",
			"confirm",
			"quit",
			"quitting",
			"exit",
			"close",
			"dialog",
			"warning",
			"prompt",
			"unsaved",
		],
	},
	{
		id: SETTING_ITEM_ID.GIT_DELETE_LOCAL_BRANCH,
		section: "git",
		title: "Delete local branch on workspace removal",
		description:
			"Also delete the local git branch when deleting a worktree workspace",
		keywords: [
			"git",
			"delete",
			"branch",
			"local",
			"worktree",
			"workspace",
			"remove",
			"cleanup",
		],
	},
	{
		id: SETTING_ITEM_ID.GIT_BRANCH_PREFIX,
		section: "git",
		title: "Branch Prefix",
		description: "Default prefix for new branch names",
		keywords: [
			"git",
			"branch",
			"prefix",
			"naming",
			"worktree",
			"author",
			"github",
			"username",
			"feat",
			"custom",
		],
	},
	{
		id: SETTING_ITEM_ID.GIT_SMART_COMMIT,
		section: "git",
		title: "Smart Commit",
		description:
			"Commit all changes when there are no staged changes (VS Code style)",
		keywords: [
			"git",
			"commit",
			"smart",
			"stage",
			"staged",
			"unstaged",
			"tracked",
			"auto",
			"all",
		],
	},
	{
		id: SETTING_ITEM_ID.GIT_AUTO_STASH,
		section: "git",
		title: "Auto Stash",
		description:
			"Stash local changes before pull/sync and restore after (VS Code style)",
		keywords: ["git", "stash", "pull", "sync", "auto", "restore", "pop"],
	},
	{
		id: SETTING_ITEM_ID.GIT_BRANCH_SORT_ORDER,
		section: "git",
		title: "Branch Sort Order",
		description:
			"Order used in the base branch picker (committer date or alphabetical)",
		keywords: [
			"git",
			"branch",
			"sort",
			"order",
			"committer",
			"date",
			"alphabetical",
			"picker",
			"pin",
			"default",
		],
	},
	{
		id: SETTING_ITEM_ID.GIT_POST_COMMIT_COMMAND,
		section: "git",
		title: "Post Commit Command",
		description:
			"Run push or sync automatically after a successful commit (VS Code style)",
		keywords: ["git", "commit", "post", "push", "sync", "auto", "after"],
	},
	{
		id: SETTING_ITEM_ID.BEHAVIOR_TELEMETRY,
		section: "behavior",
		title: "Send anonymous usage data",
		description: "Help improve Superset by sending anonymous usage data",
		keywords: [
			"telemetry",
			"analytics",
			"tracking",
			"privacy",
			"data",
			"usage",
			"anonymous",
			"metrics",
			"opt out",
			"disable",
		],
	},
	...(SUPPORTS_AGENT_SLEEP_PREVENTION
		? [
				{
					id: SETTING_ITEM_ID.BEHAVIOR_PREVENT_AGENT_SLEEP,
					section: "behavior",
					title: "Prevent system sleep during agent tasks",
					description:
						"Keep your computer awake while agents are running in Superset terminals on supported macOS and Linux systems",
					keywords: [
						"sleep",
						"mac",
						"macos",
						"linux",
						"arch",
						"awake",
						"caffeinate",
						"systemd",
						"systemd-inhibit",
						"agent",
						"claude",
						"codex",
						"terminal",
						"power",
					],
				} satisfies SettingsItem,
			]
		: []),
	{
		id: SETTING_ITEM_ID.BEHAVIOR_FILE_OPEN_MODE,
		section: "behavior",
		title: "File open mode",
		description:
			"Choose how files open when clicked in the file tree or changes view",
		keywords: [
			"file",
			"open",
			"mode",
			"split",
			"pane",
			"tab",
			"new tab",
			"split pane",
			"viewer",
			"behavior",
		],
	},
	{
		id: SETTING_ITEM_ID.BEHAVIOR_FILE_DRAG_BEHAVIOR,
		section: "behavior",
		title: "Sidebar file drag behavior",
		description:
			"Choose whether dragging files from the Files or Changes sidebar opens the file viewer or pastes file paths into terminals",
		keywords: [
			"file",
			"drag",
			"drop",
			"drag and drop",
			"sidebar",
			"files",
			"changes",
			"terminal",
			"path",
			"viewer",
			"behavior",
		],
	},
	{
		id: SETTING_ITEM_ID.BEHAVIOR_RIGHT_SIDEBAR_OPEN_VIEW_WIDTH,
		section: "behavior",
		title: "Right sidebar open view width",
		description:
			"Choose the initial width for new file and diff views opened from the Files or Git sidebar",
		keywords: [
			"right sidebar",
			"files",
			"git",
			"diff",
			"width",
			"split",
			"pane",
			"initial",
			"viewer",
			"changes",
		],
	},
	{
		id: SETTING_ITEM_ID.BEHAVIOR_RESOURCE_MONITOR,
		section: "behavior",
		title: "Resource monitor",
		description:
			"Show CPU and memory usage for workspaces and terminal sessions in the top bar",
		keywords: [
			"features",
			"resource",
			"monitor",
			"cpu",
			"memory",
			"ram",
			"usage",
			"performance",
			"process",
			"terminal",
		],
	},
	{
		id: SETTING_ITEM_ID.GIT_WORKTREE_LOCATION,
		section: "git",
		title: "Worktree location",
		description: "Base directory where new worktrees are created on disk",
		keywords: [
			"git",
			"worktree",
			"location",
			"directory",
			"path",
			"folder",
			"storage",
			"base",
			"default",
		],
	},
	{
		id: SETTING_ITEM_ID.BEHAVIOR_OPEN_LINKS_IN_APP,
		section: "behavior",
		title: "Open links in app browser",
		description:
			"Open links from chat and terminal in the built-in browser instead of your default browser",
		keywords: [
			"browser",
			"links",
			"in-app",
			"external",
			"open",
			"chat",
			"terminal",
			"url",
		],
	},
	{
		id: SETTING_ITEM_ID.BEHAVIOR_LANGUAGE_DIAGNOSTICS,
		section: "diagnostics",
		title: "Language diagnostics",
		description:
			"Choose which language services report errors and warnings in Problems",
		keywords: [
			"diagnostics",
			"problems",
			"errors",
			"warnings",
			"typescript",
			"tsx",
			"json",
			"toml",
			"dart",
			"flutter",
			"language server",
			"lint",
			"validation",
		],
	},
	{
		id: SETTING_ITEM_ID.AGENTS_ENABLED,
		section: "agents",
		title: "Enabled agents",
		description: "Control which agents appear in workspace launchers",
		keywords: [
			"agents",
			"enabled",
			"launcher",
			"dropdown",
			"visible",
			"show",
			"hide",
			"superset chat",
			"claude",
			"codex",
			"pi",
		],
	},
	{
		id: SETTING_ITEM_ID.AGENTS_COMMANDS,
		section: "agents",
		title: "Agent commands",
		description: "Configure no-prompt and prompt launch commands",
		keywords: [
			"agents",
			"commands",
			"prompt command",
			"terminal",
			"claude",
			"codex",
			"gemini",
			"opencode",
			"pi",
			"copilot",
			"cursor",
		],
	},
	{
		id: SETTING_ITEM_ID.AGENTS_TASK_PROMPTS,
		section: "agents",
		title: "Task prompt templates",
		description: "Configure task prompt templates for agent launches",
		keywords: [
			"agents",
			"task prompt",
			"template",
			"variables",
			"prompt",
			"task",
			"superset chat",
			"launch",
		],
	},
	{
		id: SETTING_ITEM_ID.TERMINAL_PRESETS,
		section: "terminal",
		title: "Terminal Presets",
		description: "Manage your terminal presets",
		keywords: [
			"terminal",
			"preset",
			"presets",
			"commands",
			"agent",
			"launch",
			"default",
			"startup",
			"config",
			"shell",
			"run",
		],
	},
	{
		id: SETTING_ITEM_ID.TERMINAL_QUICK_ADD,
		section: "terminal",
		title: "Quick Add Templates",
		description: "Pre-configured terminal presets",
		keywords: [
			"terminal",
			"quick",
			"add",
			"template",
			"claude",
			"codex",
			"gemini",
			"cursor",
			"opencode",
			"pi",
			"ai",
			"assistant",
		],
	},
	{
		id: SETTING_ITEM_ID.TERMINAL_SESSIONS,
		section: "terminal",
		title: "Active Sessions",
		description: "View and manage active terminal sessions",
		keywords: [
			"terminal",
			"sessions",
			"active",
			"running",
			"kill",
			"terminate",
			"process",
			"stop",
			"manage",
			"pty",
		],
	},
	{
		id: SETTING_ITEM_ID.TERMINAL_SUGGESTIONS,
		section: "terminal",
		title: "Shell History Suggestions",
		description: "Show command suggestions from shell history",
		keywords: [
			"terminal",
			"suggest",
			"suggestion",
			"autocomplete",
			"history",
			"shell",
			"command",
			"dropdown",
		],
	},
	{
		id: SETTING_ITEM_ID.TERMINAL_LINK_BEHAVIOR,
		section: "terminal",
		title: "Link Behavior",
		description: "How to open links from terminal",
		keywords: [
			"terminal",
			"link",
			"click",
			"open",
			"external",
			"editor",
			"file",
			"url",
			"path",
			"cmd",
			"ctrl",
			"browser",
		],
	},
	{
		id: SETTING_ITEM_ID.LINKS_FILE,
		section: "links",
		title: "File links",
		description:
			"How file paths open when clicked in terminals, chat, and tasks",
		keywords: [
			"links",
			"file",
			"click",
			"cmd",
			"ctrl",
			"shift",
			"meta",
			"pane",
			"editor",
			"external",
			"open",
			"terminal",
			"chat",
			"markdown",
			"behavior",
		],
	},
	{
		id: SETTING_ITEM_ID.LINKS_URL,
		section: "links",
		title: "URL links",
		description: "How URLs open when clicked in terminals, chat, and tasks",
		keywords: [
			"links",
			"url",
			"link",
			"click",
			"cmd",
			"ctrl",
			"shift",
			"meta",
			"browser",
			"in-app",
			"system",
			"external",
			"open",
			"terminal",
			"chat",
			"markdown",
			"behavior",
		],
	},
	{
		id: SETTING_ITEM_ID.MODELS_ANTHROPIC,
		section: "models",
		title: "Anthropic Model Auth",
		description: "Connect Anthropic for workspace naming and small model tasks",
		keywords: [
			"models",
			"anthropic",
			"claude",
			"oauth",
			"api key",
			"auth",
			"workspace naming",
			"auto name",
		],
	},
	{
		id: SETTING_ITEM_ID.MODELS_OPENAI,
		section: "models",
		title: "OpenAI Model Auth",
		description: "Connect OpenAI for supported model tasks",
		keywords: [
			"models",
			"openai",
			"gpt",
			"oauth",
			"api key",
			"auth",
			"workspace naming",
			"auto name",
		],
	},
	{
		id: SETTING_ITEM_ID.MODELS_NEXT_EDIT,
		section: "models",
		title: "Next Edit",
		description: "Configure Inception inline code completion for the editor",
		keywords: [
			"models",
			"next edit",
			"inception",
			"inline completion",
			"tab completion",
			"ghost text",
			"autocomplete",
			"api key",
			"mercury coder",
		],
	},
	{
		id: SETTING_ITEM_ID.EXPERIMENTAL_V1_MIGRATION,
		section: "experimental",
		title: "V1 to V2 Migration",
		description: "Rerun the V1 to V2 data migration",
		keywords: [
			"experimental",
			"migration",
			"migrate",
			"rerun",
			"retry",
			"recover",
			"v1",
			"v2",
			"projects",
			"workspaces",
		],
	},
	{
		id: SETTING_ITEM_ID.INTEGRATIONS_LINEAR,
		section: "integrations",
		title: "Linear",
		description: "Sync issues bidirectionally with Linear",
		keywords: [
			"integrations",
			"linear",
			"issues",
			"tasks",
			"sync",
			"connect",
			"connected",
			"project management",
		],
	},
	{
		id: SETTING_ITEM_ID.INTEGRATIONS_GITHUB,
		section: "integrations",
		title: "GitHub",
		description: "Connect repos and sync pull requests",
		keywords: [
			"integrations",
			"github",
			"repos",
			"repositories",
			"pull requests",
			"pr",
			"sync",
			"connect",
			"connected",
			"version control",
			"git",
		],
	},
	{
		id: SETTING_ITEM_ID.INTEGRATIONS_SLACK,
		section: "integrations",
		title: "Slack",
		description: "Manage tasks from Slack conversations",
		keywords: [
			"integrations",
			"slack",
			"messages",
			"conversations",
			"tasks",
			"chat",
			"sync",
			"connect",
			"connected",
			"communication",
		],
	},
	{
		id: SETTING_ITEM_ID.BILLING_OVERVIEW,
		section: "billing",
		title: "Current plan",
		description: "View your current subscription and usage",
		keywords: [
			"billing",
			"plan",
			"subscription",
			"pro",
			"free",
			"enterprise",
			"current",
			"payment",
		],
	},
	{
		id: SETTING_ITEM_ID.BILLING_PLANS,
		section: "billing",
		title: "All plans",
		description: "Compare and upgrade plans",
		keywords: [
			"billing",
			"upgrade",
			"pricing",
			"plans",
			"pro",
			"enterprise",
			"compare",
			"features",
		],
	},
	{
		id: SETTING_ITEM_ID.BILLING_USAGE,
		section: "billing",
		title: "Usage limits",
		description: "Track workspace and user limits",
		keywords: [
			"billing",
			"usage",
			"limits",
			"workspaces",
			"users",
			"quota",
			"seats",
		],
	},
	{
		id: SETTING_ITEM_ID.PROJECT_NAME,
		section: "project",
		title: "Project Name",
		description: "The name of this project",
		keywords: ["project", "name", "rename", "title", "label"],
	},
	{
		id: SETTING_ITEM_ID.PROJECT_PATH,
		section: "project",
		title: "Repository Path",
		description: "The file path to this project",
		keywords: [
			"project",
			"path",
			"repository",
			"folder",
			"directory",
			"location",
			"git",
			"repo",
			"root",
		],
	},
	{
		id: SETTING_ITEM_ID.PROJECT_SCRIPTS,
		section: "project",
		title: "Scripts",
		description: "Setup and teardown scripts for workspaces",
		keywords: [
			"project",
			"scripts",
			"setup",
			"teardown",
			"bash",
			"shell",
			"automation",
			"hooks",
			"init",
			"initialize",
			"cleanup",
			"onboarding",
			"config",
		],
	},
	{
		id: SETTING_ITEM_ID.PROJECT_BRANCH_PREFIX,
		section: "project",
		title: "Branch Prefix",
		description: "Override the default branch prefix for this project",
		keywords: [
			"project",
			"branch",
			"prefix",
			"naming",
			"git",
			"worktree",
			"author",
			"github",
			"username",
			"feat",
			"custom",
			"override",
		],
	},
	{
		id: SETTING_ITEM_ID.PROJECT_WORKTREE_LOCATION,
		section: "project",
		title: "Worktree Location",
		description: "Override the global worktree directory for this project",
		keywords: [
			"project",
			"worktree",
			"location",
			"directory",
			"path",
			"folder",
			"storage",
			"override",
		],
	},
	{
		id: SETTING_ITEM_ID.PROJECT_IMPORT_WORKTREES,
		section: "project",
		title: "Import Worktrees",
		description: "Import existing worktrees from disk into Superset",
		keywords: [
			"project",
			"import",
			"worktree",
			"worktrees",
			"workspace",
			"workspaces",
			"external",
			"existing",
			"disk",
			"add",
		],
	},
	{
		id: SETTING_ITEM_ID.PROJECT_AUTO_IMPORT_WORKTREES,
		section: "project",
		title: "Auto-import detected worktrees",
		description:
			"Automatically import worktrees created outside Superset (e.g. by LLM agents)",
		keywords: [
			"project",
			"auto",
			"automatic",
			"import",
			"worktree",
			"worktrees",
			"detect",
			"llm",
			"claude",
			"agent",
		],
	},
	{
		id: SETTING_ITEM_ID.PROJECT_AUTO_REMOVE_WORKTREES,
		section: "project",
		title: "Auto-remove missing worktrees",
		description:
			"Automatically remove worktrees from the sidebar when they are deleted from disk",
		keywords: [
			"project",
			"auto",
			"automatic",
			"remove",
			"delete",
			"cleanup",
			"missing",
			"worktree",
			"worktrees",
			"orphan",
			"sync",
		],
	},
	{
		id: SETTING_ITEM_ID.PROJECT_ENV_VARS,
		section: "project",
		title: "Environment Variables",
		description: "Manage environment variables and secrets for cloud sandboxes",
		keywords: [
			"environment",
			"variables",
			"secrets",
			"env",
			"cloud",
			"sandbox",
		],
	},
	{
		id: SETTING_ITEM_ID.API_KEYS_LIST,
		section: "apikeys",
		title: "API Keys",
		description: "Manage API keys for MCP server access",
		keywords: [
			"api",
			"key",
			"keys",
			"mcp",
			"claude",
			"integration",
			"external",
			"access",
			"token",
			"authentication",
		],
	},
	{
		id: SETTING_ITEM_ID.API_KEYS_GENERATE,
		section: "apikeys",
		title: "Generate API Key",
		description: "Create new API keys for external integrations",
		keywords: [
			"api",
			"key",
			"generate",
			"create",
			"new",
			"mcp",
			"claude desktop",
			"claude code",
		],
	},
	{
		id: SETTING_ITEM_ID.EXTENSIONS_BROWSER,
		section: "extensions",
		title: "Browser Extensions",
		description:
			"Install and manage Chrome extensions from the Chrome Web Store",
		keywords: [
			"extensions",
			"chrome",
			"browser",
			"web store",
			"addon",
			"plugin",
			"install",
			"crx",
		],
	},
	{
		id: SETTING_ITEM_ID.VSCODE_EXTENSIONS_MANAGE,
		section: "vscodeExtensions",
		title: "VS Code Extensions",
		description:
			"Manage VS Code extensions like Claude Code, ChatGPT, and Kimi Code running inside Superset",
		keywords: [
			"vscode",
			"vs code",
			"extension",
			"claude",
			"chatgpt",
			"codex",
			"kimi",
			"ai",
			"install",
			"manage",
		],
	},
	{
		id: SETTING_ITEM_ID.VSCODE_EXTENSIONS_INDENT_RAINBOW,
		section: "vscodeExtensions",
		title: "Indent Rainbow",
		description:
			"Colorize indentation levels in the code editor with customizable rainbow colors",
		keywords: [
			"indent",
			"rainbow",
			"color",
			"indentation",
			"editor",
			"highlight",
		],
	},
	{
		id: SETTING_ITEM_ID.VSCODE_EXTENSIONS_TRAILING_SPACES,
		section: "vscodeExtensions",
		title: "Trailing Spaces",
		description:
			"Highlight trailing whitespace at the end of lines in the code editor",
		keywords: [
			"trailing",
			"spaces",
			"whitespace",
			"trim",
			"editor",
			"highlight",
		],
	},
	{
		id: SETTING_ITEM_ID.VSCODE_EXTENSIONS_REFERENCE_GRAPH,
		section: "vscodeExtensions",
		title: "Reference Graph",
		description:
			"Visualize code symbol references and call hierarchies as interactive graphs",
		keywords: [
			"reference",
			"graph",
			"call",
			"hierarchy",
			"symbol",
			"visualization",
			"editor",
		],
	},
	{
		id: SETTING_ITEM_ID.METRICS_GITHUB_OVERVIEW,
		section: "metrics",
		title: "GitHub Overview",
		description:
			"GitHub sync health, active workspaces, rate limits, and scheduler state",
		keywords: [
			"metrics",
			"github",
			"overview",
			"health",
			"rate limit",
			"scheduler",
			"debug",
			"sync",
			"status",
		],
	},
	{
		id: SETTING_ITEM_ID.METRICS_GITHUB_TRAFFIC,
		section: "metrics",
		title: "GitHub Traffic",
		description:
			"Operation volume, cache efficiency, and workspace-level GitHub activity",
		keywords: [
			"metrics",
			"github",
			"traffic",
			"cache",
			"efficiency",
			"calls",
			"api",
			"preview",
			"comments",
		],
	},
	{
		id: SETTING_ITEM_ID.METRICS_GITHUB_COPY,
		section: "metrics",
		title: "GitHub Debug Copy",
		description:
			"Copy summary, JSON bundle, and repro template for GitHub sync debugging",
		keywords: [
			"metrics",
			"github",
			"copy",
			"debug bundle",
			"repro",
			"json",
			"support",
			"diagnostics",
		],
	},
	{
		id: SETTING_ITEM_ID.SERVICE_STATUS_PROVIDERS,
		section: "serviceStatus",
		title: "Service Status Providers",
		description:
			"Manage which external status pages appear in the header (Claude, Codex, GitHub, …)",
		keywords: [
			"service status",
			"status",
			"providers",
			"statuspage",
			"external",
			"header",
			"indicator",
			"health",
			"uptime",
			"incident",
			"dashboard",
		],
	},
	{
		id: SETTING_ITEM_ID.SERVICE_STATUS_ADD,
		section: "serviceStatus",
		title: "Add Custom Status Provider",
		description:
			"Add a Statuspage.io-compatible provider with a custom label and icon",
		keywords: [
			"add service status",
			"new provider",
			"custom",
			"statuspage",
			"api",
			"favicon",
			"icon",
			"upload",
			"url",
		],
	},
	{
		id: SETTING_ITEM_ID.PERMISSIONS_FULL_DISK_ACCESS,
		section: "permissions",
		title: "Full Disk Access",
		description:
			"Persistent access to Documents, Downloads, Desktop, and iCloud from terminal sessions",
		keywords: [
			"permissions",
			"full disk access",
			"fda",
			"files",
			"documents",
			"downloads",
			"desktop",
			"icloud",
			"macos",
			"security",
			"privacy",
		],
	},
	{
		id: SETTING_ITEM_ID.PERMISSIONS_ACCESSIBILITY,
		section: "permissions",
		title: "Accessibility",
		description:
			"Send keystrokes, manage windows, and control other applications",
		keywords: [
			"permissions",
			"accessibility",
			"a11y",
			"keystrokes",
			"window management",
			"macos",
			"security",
			"privacy",
			"trusted",
		],
	},
	{
		id: SETTING_ITEM_ID.PERMISSIONS_MICROPHONE,
		section: "permissions",
		title: "Microphone",
		description: "Use voice transcription and push-to-talk features",
		keywords: [
			"permissions",
			"microphone",
			"mic",
			"voice",
			"transcription",
			"audio",
			"recording",
			"push to talk",
			"codex",
			"privacy",
		],
	},
	{
		id: SETTING_ITEM_ID.PERMISSIONS_CAMERA,
		section: "permissions",
		title: "Camera",
		description:
			"Use video input in websites and tools running inside Superset",
		keywords: [
			"permissions",
			"camera",
			"webcam",
			"video",
			"recording",
			"capture",
			"privacy",
			"browser",
			"website",
		],
	},
	{
		id: SETTING_ITEM_ID.PERMISSIONS_APPLE_EVENTS,
		section: "permissions",
		title: "Automation",
		description: "Run terminal commands and interact with other applications",
		keywords: [
			"permissions",
			"automation",
			"apple events",
			"applescript",
			"macos",
			"security",
			"privacy",
			"system events",
		],
	},
	{
		id: SETTING_ITEM_ID.PERMISSIONS_LOCAL_NETWORK,
		section: "permissions",
		title: "Local Network",
		description: "Discover and connect to development servers on your network",
		keywords: [
			"permissions",
			"local network",
			"bonjour",
			"mdns",
			"macos",
			"security",
			"privacy",
			"development servers",
		],
	},
	{
		id: SETTING_ITEM_ID.SECURITY_EXPOSE_HOST_SERVICE_VIA_RELAY,
		section: "security",
		title: "Allow remote workspaces to access this device via relay",
		description:
			"Controls whether remote workspaces can reach your local host service through the Superset relay",
		keywords: [
			"security",
			"relay",
			"remote",
			"workspace",
			"expose",
			"lockdown",
			"network",
			"inbound",
			"host service",
			"tunnel",
			"attack surface",
		],
	},
	{
		id: SETTING_ITEM_ID.HOST_MEMBERS,
		section: "hosts",
		title: "Host members",
		description: "View who has access to a host in your organization",
		keywords: [
			"host",
			"hosts",
			"member",
			"members",
			"access",
			"team",
			"share",
			"machine",
			"device",
		],
	},
	{
		id: SETTING_ITEM_ID.HOST_INVITE_MEMBER,
		section: "hosts",
		title: "Grant access to a host",
		description: "Add an organization member to a host",
		keywords: [
			"host",
			"hosts",
			"invite",
			"add",
			"grant",
			"member",
			"access",
			"share",
		],
	},
	{
		id: SETTING_ITEM_ID.HOST_MEMBER_ROLE,
		section: "hosts",
		title: "Host member role",
		description: "Change a member's role on a host (owner or member)",
		keywords: [
			"host",
			"hosts",
			"role",
			"owner",
			"member",
			"permission",
			"admin",
		],
	},
];

export function searchSettings(query: string): SettingsItem[] {
	if (!query.trim()) return SETTINGS_ITEMS;

	const words = query
		.toLowerCase()
		.split(/\s+/)
		.filter((w) => w.length > 0);
	if (words.length === 0) return SETTINGS_ITEMS;

	return SETTINGS_ITEMS.filter((item) => {
		const haystack = [
			item.title.toLowerCase(),
			item.description.toLowerCase(),
			...item.keywords.map((kw) => kw.toLowerCase()),
		].join(" ");
		return words.every((word) => haystack.includes(word));
	});
}

export function getMatchCountBySection(
	query: string,
): Partial<Record<SettingsSection, number>> {
	const matches = searchSettings(query);
	const counts: Partial<Record<SettingsSection, number>> = {};

	for (const item of matches) {
		counts[item.section] = (counts[item.section] || 0) + 1;
	}

	return counts;
}

export function getMatchingItemsForSection(
	query: string,
	section: SettingsSection,
): SettingsItem[] {
	return searchSettings(query).filter((item) => item.section === section);
}

export function isItemVisible(
	itemId: SettingItemId,
	visibleItems: SettingItemId[] | null | undefined,
): boolean {
	return !visibleItems || visibleItems.includes(itemId);
}
