// AUTO-GENERATED by scripts/sync-aivis-presets.ts
// Do not edit by hand. Re-run the script to refresh.

import icon5 from "renderer/assets/aivis-models/zonoko.jpg";
import sample5 from "renderer/assets/aivis-models/zonoko.wav";
import icon0 from "renderer/assets/aivis-models/まい.jpg";
import sample0 from "renderer/assets/aivis-models/まい.wav";
import icon7 from "renderer/assets/aivis-models/まお.jpg";
import sample7 from "renderer/assets/aivis-models/まお.m4a";
import icon2 from "renderer/assets/aivis-models/るな.jpg";
import sample2 from "renderer/assets/aivis-models/るな.wav";
import icon6 from "renderer/assets/aivis-models/コハク.jpg";
import sample6 from "renderer/assets/aivis-models/コハク.m4a";
import icon4 from "renderer/assets/aivis-models/中2.jpg";
import sample4 from "renderer/assets/aivis-models/中2.m4a";
import icon8 from "renderer/assets/aivis-models/天深シノ.jpg";
import sample8 from "renderer/assets/aivis-models/天深シノ.wav";
import icon3 from "renderer/assets/aivis-models/桜音.jpg";
import sample3 from "renderer/assets/aivis-models/桜音.wav";
import icon1 from "renderer/assets/aivis-models/花音.jpg";
import sample1 from "renderer/assets/aivis-models/花音.wav";

export interface AivisPresetModel {
	uuid: string;
	name: string;
	iconAsset: string | null;
	sampleAsset: string | null;
	authorName: string | null;
}

export const AIVIS_PRESET_MODELS: AivisPresetModel[] = [
	{
		uuid: "e9339137-2ae3-4d41-9394-fb757a7e61e6",
		name: "まい",
		iconAsset: icon0,
		sampleAsset: sample0,
		authorName: "魔法プログラム",
	},
	{
		uuid: "a670e6b8-0852-45b2-8704-1bc9862f2fe6",
		name: "花音",
		iconAsset: icon1,
		sampleAsset: sample1,
		authorName: "魔法プログラム",
	},
	{
		uuid: "4f281e78-eba6-495a-8e50-5c322d02b5b1",
		name: "るな",
		iconAsset: icon2,
		sampleAsset: sample2,
		authorName: "魔法プログラム",
	},
	{
		uuid: "3328da9a-8124-4619-a853-f7fc2f37889f",
		name: "桜音",
		iconAsset: icon3,
		sampleAsset: sample3,
		authorName: "魔法プログラム",
	},
	{
		uuid: "9107b8b6-1ed1-43f5-bebe-0de4df4d229d",
		name: "中2",
		iconAsset: icon4,
		sampleAsset: sample4,
		authorName: "魔法プログラム",
	},
	{
		uuid: "7fc08a41-b64d-456d-8b22-8e1284674775",
		name: "zonoko",
		iconAsset: icon5,
		sampleAsset: sample5,
		authorName: "ずごっく",
	},
	{
		uuid: "22e8ed77-94fe-4ef2-871f-a86f94e9a579",
		name: "コハク",
		iconAsset: icon6,
		sampleAsset: sample6,
		authorName: "オズチャット -Oz Chat-",
	},
	{
		uuid: "a59cb814-0083-4369-8542-f51a29e72af7",
		name: "まお",
		iconAsset: icon7,
		sampleAsset: sample7,
		authorName: "オズチャット -Oz Chat-",
	},
	{
		uuid: "0f6821f4-9f86-4da1-a41a-fbe6fff9ca88",
		name: "天深シノ",
		iconAsset: icon8,
		sampleAsset: sample8,
		authorName: "天深シノ・亜空マオ",
	},
];
